server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /chat/assets/ {
        try_files $uri =404;
    }

    location /chat/ {
        try_files $uri $uri/ /chat/index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain application/json application/javascript text/css;
}